<x-layouts.admin title="Buku">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-3xl font-bold">Buku</h1><p class="mt-2 text-slate-600">Kelola metadata, file, dan status pemrosesan.</p></div>@can('books.create')<a href="{{ route('admin.books.create') }}" class="rounded-lg bg-red-700 px-5 py-2.5 text-center font-semibold text-white hover:bg-red-800">Tambah buku</a>@endcan</div>
    <form method="GET" class="mt-6 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_220px_auto]">
        <label class="text-sm font-medium">Cari judul<input name="q" value="{{ request('q') }}" class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2"></label>
        <label class="text-sm font-medium">Status<select name="status" class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">Semua</option>@foreach(\App\Enums\BookStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->name }}</option>@endforeach</select></label>
        <button class="self-end rounded-lg border border-slate-300 px-4 py-2 font-semibold">Terapkan</button>
    </form>
    <div class="mt-5 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr><th class="px-4 py-3">Judul</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Proses PDF</th><th class="px-4 py-3">Tahun</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($books as $book)<tr><td class="px-4 py-4"><p class="font-semibold">{{ $book->title }}</p><p class="text-xs text-slate-500">{{ $book->slug }}</p></td><td class="px-4 py-4">{{ $book->status->value }}</td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-xs {{ $book->processing_status->value === 'failed' ? 'bg-red-100 text-red-800' : 'bg-slate-100' }}">{{ $book->processing_status->value }}</span></td><td class="px-4 py-4">{{ $book->publication_year ?? '—' }}</td><td class="px-4 py-4 text-right">@can('books.update')<a href="{{ route('admin.books.edit',$book) }}" class="font-semibold text-red-700">Edit</a>@endcan</td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-slate-500">Belum ada buku.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-5">{{ $books->links() }}</div>
</x-layouts.admin>

